# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YkW7QTnjwydfFZYd8Eh9dZOaZgWkUupt
"""

# 1. FastAPI 설치 (Colab 환경에 임시 설치)
!pip install fastapi uvicorn

# 2. 아주 간단한 API 코드 작성
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def home():
    return {"message": "Hello! Render 서버가 정상 작동 중입니다."}

@app.get("/test-calc")
def test_calc(a: int, b: int):
    # 두 숫자를 받아 더해주는 예제 API (나중에 비행기 좌표 계산 수식이 들어갈 자리)
    result = a + b
    return {
        "status": "success",
        "input_a": a,
        "input_b": b,
        "sum": result
    }

print("코드 실행 완료!")

